// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsxysujsqoholqaqjrpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzeHlzdWpzcW9ob2xxYXFqcnBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNzgyMjcsImV4cCI6MjA2NDY1NDIyN30.6DTzRzVSbIIfxQD7A1hZlKtw84IRtO1jmCgqk5UVIQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);